version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: shop-image
    container_name: shop-container
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./item:/app/item
    working_dir: /app

volumes:
  postgres-data:

#services:
#  db:
#    image: mysql:latest
#    container_name: mysql-container
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: shop
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  app:
#    build: .
#    image: shop-image
#    container_name: shop-container
#    ports:
#      - "8088:8088"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shop?serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./item:/app/item
#    working_dir: /app
#
#volumes:
#  mysql-data: