spring:
  application:
    name: shop

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_LOCAL_URL}
    #url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    #?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        #default_schema: shop
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 100MB

  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

itemImgLocation: /app/item
uploadPath: file:///app
#itemImgLocation: C:\Users\USER\Desktop\code\Spring\shop\item
#uploadPath: file:///C:\Users\USER\Desktop\code\Spring\shop


logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  #port: ${PORT:8080}
  port: 8088

