spring:
  application:
    name: shop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    #?createDatabaseIfNotExist=true
    username: root
    password: sam5754752

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 100MB

  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

itemImgLocation: /app/item
uploadPath: file:///app


logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8088

